### ISSUE TITLE
Cannot read property 'totalRespondents' of undefined

### ISSUE THREAD

**Issue by adriaanvanrossum** [lirantal/typeform-export-excel#10]
When running

```bash
$ typeform-export-excel --apiKey test1234 --formId iGifhW --filename survey-results.xlsx --author Adriaan
```

## Expected Behavior

I expect it to create a download file.

## Current Behavior

```bash
Error: Cannot read property 'totalRespondents' of undefined
```

## Context

Just want to download the questions, because I can't export them in the Typeform itself.

## Your Environment

- Library Version used: typeform-export-excel@1.0.5
- Node.js version (e.g. Node.js 5.4): v13.0.1
- Operating System and version (desktop or mobile): desktop

**Comment by adriaanvanrossum** [comment]
I found a way for my issue, you can download all data via the tool: https://admin.typeform.com/account

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/69113842-bf6ae200-0ab6-11ea-97df-d63c129a7777.jpg"></kbd>

I will keep this issue open for if you want to dig into this @lirantal, feel free to close it.

**Comment by lirantal** [comment]
hey @adriaanvanrossum, thanks for chiming in on the error.
is it possible that there aren't any questions yet on the form? or perhaps no responses made?

p.s. I know that there's a way to export to spreadsheet from typeform itself but the format you get is hard to process IMO and this version of it with the module organizes the data much easier.

**Comment by adriaanvanrossum** [comment]
> is it possible that there aren't any questions yet on the form? or perhaps no responses made?

I had 80 responses on more or less 20 questions. I did export that same form to excel inside the Typeform app, which kind of worked.

If I need to test something for you, let me know. O wait, I did delete my Typeform account, so that would not be too helpful. Sorry.

**Comment by lirantal** [comment]
I just tried with my own typeform account and form and I wasn't able to reproduce this problem.
If you were able to reproduce re-open the issue and I can try debugging it further with you.

Thanks for spending time to let me know regardless!
